### ISSUE TITLE
Clever install clever-auth issues

### ISSUE THREAD

**Issue by MauritzKruger** [CleverStack/clever-auth#18]
I get the following when trying to install clever-auth, clever-cli is on version 1.1.4, created new project with init and then I get this when adding module:
clever install clever-auth
Attempting to install clever-auth...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-auth...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-auth
  ├── Installing modules: clever-accounts clever-users
✔      Found CleverStack Backend (node-seed) in /vagrant/cs-latest/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-accounts...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-accounts...
✔    Successfully installed clever-accounts...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-accounts
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-users

/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33
      throw new Error('Circular dependency: '+dep);
            ^
Error: Circular dependency: clever-users
    at /usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33:13
    at Array.forEach (native)
    at DepTree.resolveNode (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
    at /usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:35:10
    at Array.forEach (native)
    at DepTree.resolveNode (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
    at DepTree.resolve (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:49:10)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:107:44)
    at EventEmitter.emit (events.js:92:17)
    at finish (/usr/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:107:17)

**Comment by pilsy** [comment]
I just published clever-accounts@1.0.2 to fix this, can you confirm if it has for you as well?

**Comment by MauritzKruger** [comment]
Problem fixed with clever-accounts and clever-users, but now clever-roles is giving following feedback:
clever install clever-auth
Attempting to install clever-auth...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-auth...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-auth
  ├── Installing modules: clever-accounts clever-users
✔      Found CleverStack Backend (node-seed) in /vagrant/cs-latest/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-accounts...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-accounts...
✔    Successfully installed clever-accounts...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-accounts
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-users
  ├── Installing modules: clever-roles
✔      Found CleverStack Backend (node-seed) in /vagrant/cs-latest/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-roles...
  ├── Installing NPM modules for clever-roles...
✔    Successfully installed clever-roles...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-roles

/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33
      throw new Error('Circular dependency: '+dep);
            ^
Error: Circular dependency: clever-accounts
    at /usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33:13
    at Array.forEach (native)
    at DepTree.resolveNode (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
    at /usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:35:10
    at Array.forEach (native)
    at DepTree.resolveNode (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
    at /usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:35:10
    at Array.forEach (native)
    at DepTree.resolveNode (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
    at DepTree.resolve (/usr/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:49:10)

**Comment by pilsy** [comment]
This has been fixed in https://github.com/CleverStack/clever-orm/issues/34 i believe, let me know if it hasn't :)
