### ISSUE TITLE
Error During Injection, can't find factory for UserService

### ISSUE THREAD

**Issue by yasirhantoush** [CleverStack/clever-auth#19]
Any ideas ? couldn't get the module running.

**Comment by pilsy** [comment]
Hi @yasirhantoush, thanks for reporting this :+1: 

I need to release a new version of the module for it to work with the latest CLI and Node-Seed (see https://github.com/CleverStack/clever-auth/compare/1.2.3...master)

I need to fix the tests for travis to pass the build, but have been busy lately with work, refactoring and lots of documentation - But i will take a look at this within the next 24 hours for you ;)

**Comment by pilsy** [comment]
Btw, if you needed to use the module before then - you can simply clone this repo into your modules/clever-auth folder using git - then run `clever setup` and `grunt prompt:cleverAuthConfig`

**Comment by pilsy** [comment]
The tests have been fixed https://travis-ci.org/CleverStack/clever-auth/builds/55238929 - just releasing a new version of this module now.

**Comment by pilsy** [comment]
clever-auth 1.2.5 has just been released, https://github.com/CleverStack/clever-auth/releases/tag/1.2.5

this should fix the error you had, let me know if there are anymore issues :+1:

**Comment by elBarkey** [comment]
same error happened in 1.2.6 version

**Comment by pilsy** [comment]
@elBarkey do you mean clever-auth@1.2.6  or cleverstack-cli@1.2.6?

**Comment by andresmeidla** [comment]
the clever-auth readme says:
* Use with the clever-users module - OR - with any other module that exports the UserController, UserService and UserModel resources/classes.

so a quick fix would be
```
clever install clever-users
```
then, in the backend directory, run
```
grunt db
```
to create the database entities
